dataset:
  limit_data: 10000

model:
  tokenization: octuple

training:
  max_epochs: 3
  fast_dev_run: false

misc:
  task: genre
  output_dir: output/finetune_genre_sample
  run_name: sample-genre
  model_path: null
